//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMSample.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVMSample.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVVM Sample App. Version 1.0. © 2013.
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        internal static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying Updates....
        /// </summary>
        internal static string ApplyingUpdates {
            get {
                return ResourceManager.GetString("ApplyingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        internal static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        internal static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Customer....
        /// </summary>
        internal static string CreatingCustomer {
            get {
                return ResourceManager.GetString("CreatingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Product....
        /// </summary>
        internal static string CreatingProduct {
            get {
                return ResourceManager.GetString("CreatingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Confirmation.
        /// </summary>
        internal static string CustomerConfirmation {
            get {
                return ResourceManager.GetString("CustomerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create this customer?.
        /// </summary>
        internal static string CustomerConfirmationMessage {
            get {
                return ResourceManager.GetString("CustomerConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Updates....
        /// </summary>
        internal static string DownloadingUpdates {
            get {
                return ResourceManager.GetString("DownloadingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTS:.
        /// </summary>
        internal static string DTSLabel {
            get {
                return ResourceManager.GetString("DTSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Type:.
        /// </summary>
        internal static string EngineTypeLabel {
            get {
                return ResourceManager.GetString("EngineTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving to database.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS:.
        /// </summary>
        internal static string GPSLabel {
            get {
                return ResourceManager.GetString("GPSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inboard.
        /// </summary>
        internal static string Inboard {
            get {
                return ResourceManager.GetString("Inboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet.
        /// </summary>
        internal static string Jet {
            get {
                return ResourceManager.GetString("Jet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick:.
        /// </summary>
        internal static string JoystickLabel {
            get {
                return ResourceManager.GetString("JoystickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        internal static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        internal static string LengthLabel {
            get {
                return ResourceManager.GetString("LengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make:.
        /// </summary>
        internal static string MakeLabel {
            get {
                return ResourceManager.GetString("MakeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        internal static string ModelLabel {
            get {
                return ResourceManager.GetString("ModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Customer Fields.
        /// </summary>
        internal static string OptionalCustomerFields {
            get {
                return ResourceManager.GetString("OptionalCustomerFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Product Fields.
        /// </summary>
        internal static string OptionalProductFields {
            get {
                return ResourceManager.GetString("OptionalProductFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outboard.
        /// </summary>
        internal static string Outboard {
            get {
                return ResourceManager.GetString("Outboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description:.
        /// </summary>
        internal static string ProductDescriptionLabel {
            get {
                return ResourceManager.GetString("ProductDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        internal static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type:.
        /// </summary>
        internal static string ProductTypeLabel {
            get {
                return ResourceManager.GetString("ProductTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Customer Fields.
        /// </summary>
        internal static string RequiredCustomerFields {
            get {
                return ResourceManager.GetString("RequiredCustomerFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Product Fields.
        /// </summary>
        internal static string RequiredProductFields {
            get {
                return ResourceManager.GetString("RequiredProductFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        internal static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterndrive.
        /// </summary>
        internal static string Sterndrive {
            get {
                return ResourceManager.GetString("Sterndrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved to database!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunroof:.
        /// </summary>
        internal static string SunroofLabel {
            get {
                return ResourceManager.GetString("SunroofLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Speed:.
        /// </summary>
        internal static string TopSpeedLabel {
            get {
                return ResourceManager.GetString("TopSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates Failed.
        /// </summary>
        internal static string UpdatesFailed {
            get {
                return ResourceManager.GetString("UpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates Successful!.
        /// </summary>
        internal static string UpdatesSuccessful {
            get {
                return ResourceManager.GetString("UpdatesSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Customers.
        /// </summary>
        internal static string ViewCustomers {
            get {
                return ResourceManager.GetString("ViewCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Products.
        /// </summary>
        internal static string ViewProducts {
            get {
                return ResourceManager.GetString("ViewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVVM Sample App.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspaces.
        /// </summary>
        internal static string Workspaces {
            get {
                return ResourceManager.GetString("Workspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string YearLabel {
            get {
                return ResourceManager.GetString("YearLabel", resourceCulture);
            }
        }
    }
}
